### ISSUE TITLE
No package.json file found

### ISSUE THREAD

**Issue by camueller** [gkushang/cucumber-html-reporter#142]
Defaults are use for name and version since the package.json is not found even though being located in the same directory as the script:

```
axel@t540:~/WebstormProjects/frontend$ node report.js
No package.json file found in: /home/axel/WebstormProjects/frontend/package.json, using default name and version.
Cucumber HTML report reports/report.html generated successfully.
axel@t540:~/WebstormProjects/frontend$ ls -al package.json 
-rw-rw-r-- 1 axel axel 719 Apr 30 12:06 package.json
```

Content of report.js is almost the same as the example you provided:
```
var reporter = require('cucumber-html-reporter');

var options = {
  theme: 'bootstrap',
  jsonFile: 'reports/report.json',
  output: 'reports/report.html',
  reportSuiteAsScenarios: true,
  metadata: {
    "App Version": "0.3.2",
    "Test Environment": "STAGING",
    "Browser": "Chrome  54.0.2840.98",
    "Platform": "Windows 10",
    "Parallel": "Scenarios",
    "Executed": "Remote"
  }
};

reporter.generate(options);

```

**Comment by gkushang** [comment]
@camueller 

Sorry for getting late on this. Are you still seeing the issue? If so, please feel free to reopen the issue and provide the steps to reproduce. At first glance, it looked like an issue in your project's Package.json. Otherwise, this reporter escapes the validation if not found - https://github.com/gkushang/cucumber-html-reporter/blob/develop/lib/reporter.js#L54
