### ISSUE TITLE
Stop inlining screenshots?

### ISSUE THREAD

**Issue by joeboon** [gkushang/cucumber-html-reporter#145]
When configured to store screenshot files using "storeScreenshots: true," I was expecting it to stop storing them inline in the HTML. So the screenshots are stored in files, but not referenced by the HTML, and are duplicates inline in the HTML. This is using twice the disk space. Have I misunderstood this setting?

If correct, are there any objections to adding a new option "inlineScreenshots" which defaults to true? When false, the HTML report would include the image using an img tag, and link to the image file.

**Comment by gkushang** [comment]
@joeboon 

`storeScreenshots` is a flag which store screenshots locally on the disk if `storeScreenshots:true` otherwise it would only include on HTML report. In anycase, either true or false, the screenshots would be on HTML as inline. This flag does not control the Inline Screenshots. 

Please create the _feature request_ if you are looking for any specific feature.

**Comment by joeboon** [comment]
Thank you for the clarification.
