### ISSUE TITLE
The reporter doesn't create Json file if it doesn't exist !

### ISSUE THREAD

**Issue by igniteram** [gkushang/cucumber-html-reporter#5]
The reporter throws error if it doesn't find any json file in ``` options.jsonFile``` , but it takes already created json file. Is this the way it is implemented or am I doing somethin wrong here??

**Comment by gkushang** [comment]
`options.jsonFile` is an optional parameter. If not passed, reporter will build a path from the value of `options.output`. 

E.g. 
```
var options = {
                theme: theme,
                output: 'test/report/cucumber_report.html',
                reportSuiteAsScenarios: true
            };
```
From above options, it will look for the JSON file named `'test/report/cucumber_report.html.json` since `jsonFile` hasn't passed to the options.

However, this reporter won't generate the JSON file but it will read the JSON and coverts to HTML. Please checkout the updated [README USAGE](https://github.com/gkushang/cucumber-html-reporter/blob/develop/README.md#usage) on how to generate JSON file from cucumberJs/for more info.

HTH

**Comment by igniteram** [comment]
Ok in a nutshell, the reporter just reads an already created JSON file and will convert it into html file. It will not create if the JSON file doesn't exist!
